kind: Service
apiVersion: v1
metadata:
  name: etcd-discovery
  creationTimestamp: 
  labels:
    name: etcd-discovery
    heritage: helm
    provider: etcd
spec:
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
    nodePort: 0
  selector:
    name: etcd-discovery
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

