apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
    heritage: helm
    provider: nodejs-mongodb
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo:3.2.3
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
