apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
    heritage: helm
    provider: nodejs-mongodb
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
