apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    heritage: helm
    provider: nodejs-mongodb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: web
