apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
    heritage: helm
    provider: nodejs-mongodb
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: meanjs/mean
        name: web
        ports:
        - containerPort: 8080 
          name: http-server
